---
development:
  cloud_name: dnt6n42lu
  api_key: '451811775293429'
  api_secret: ZH-BTWtMLggsUgVEG3DsHqE3oQo
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dnt6n42lu
  api_key: '451811775293429'
  api_secret: ZH-BTWtMLggsUgVEG3DsHqE3oQo
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dnt6n42lu
  api_key: '451811775293429'
  api_secret: ZH-BTWtMLggsUgVEG3DsHqE3oQo
  enhance_image_tag: true
  static_image_support: false
